apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dependencies
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/oscarsjlh/todo-app
        revision: main
        directories:
          - path: k8s/apps/*
  template:
    metadata:
      name: "{{.path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/oscarsjlh/todo-app
        targetRevision: main
        helm:
          releaseName: "{{.path.basename}}"
          valueFiles:
            - "Values.yaml"
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
