apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  namespace: todo
  labels:
    app: todo
spec:
  selector:
    matchLabels:
      app: todo 
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo-api 
        image: 477601539816.dkr.ecr.eu-west-2.amazonaws.com/todo-app:latest@sha256:f199707b7992af56d4e30635e59f10ec9bcec2379ed35794640e8ede42b7dc47
        ports:
        - containerPort: 3000
      env:
      - name: DB_USER 
        value: todo 
      - name: DB_NAME
        value: todo
      - name: DB_HOST
        value: todo-db.cr3zlwandrth.eu-west-2.rds.amazonaws.com:5432 
      - name: PRODUCTION
        value: "true"
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef: secrets
        name: todo-db-secret
        key: db-pass-todo
