apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  namespace: todo
  labels:
    app: todo
spec:
  selector:
    matchLabels:
      app: todo 
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo-api 
        image: {{ .Values.imageRepository }}:latest@{{ .Values.imageSha }}
        ports:
        - containerPort: 3000
        env:
          - name: DB_USER 
            value: todo 
          - name: DB_NAME
            value: todo
          - name: DB_HOST
            value: {{ .Values.dbHostname }}
          - name: PRODUCTION
            value: "true"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: secrets 
                key: db-pass-todo
