apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-sa
  namespace: todo
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: secret-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: todo-sec
  namespace: todo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-sa
    kind: SecretStore
  target:
    name: secrets
    creationPolicy: Owner
  data:
    - secretKey: db-pass-todo
      remoteRef:
        key: db-pass-new
