version: "3.8"
services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pa55word
      - POSTGRES_DB=tasks
    ports:
      - "5432:5432"
    volumes:
      - /home/oscar/volumes/db:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      TODO_DB_DSN: "postgres://postgres:pa55word@db:5432/tasks?sslmode=disable"
  test:
    image: play-test
volumes:
  db:
    driver: local
