name: ecr build

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: "eu-west-2"
  AWS_ACCOUNT_ID: "477601539816"
  TAGS: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ github.event.repository.name }}
jobs:
  deploy:
    name: Push to ECR
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-${{ github.event.repository.name }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ."{{defaultContext}}:src"
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
