name: ecr build

on:
  push:
    paths:
      - src/**
    branches: ["main"]

env:
  AWS_REGION: "eu-west-2"
  AWS_ACCOUNT_ID: "477601539816"
  TAGS: "477601539816.dkr.ecr.eu-west-2.amazonaws.com/todo-app"
jobs:
  deploy:
    name: Push to ECR
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: checkout
        with:
          ssh-key: ${{ secrets.BOT_ACCESS_TOKEN }}
        uses: actions/checkout@v4
      - name: setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-oscar-todo-app-todo-app
          aws-region: ${{ env.AWS_REGION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:src"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          platforms: linux/amd64
          tags: ${{ env.TAGS }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Update manifest
        working-directory: ./k8s/todo-template
        run: |
          echo 'Sha digest is: ${{ steps.build.outputs.digest }}'
          sha="${{ github.sha }}"
          sed -i "s/\(imageTag: \).*/\1$sha/" Values.yaml
          git config --global user.name 'Img updater'
          git config --global user.emal 'imgupdater@noreply.com'
          git commit -am "Update sha to $sha"
          git push
